version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "build"]
    volumes:
      - frontend_dist:/app/dist
    # no ports! it's only for building React
    depends_on:
      - web

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
      - frontend_dist:/app/frontend_dist
    ports:
      - "80:80"
    depends_on:
      - web
      - frontend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: budgetdb
      MYSQL_USER: budgetuser
      MYSQL_PASSWORD: budgetpassword
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  frontend_dist:
